apiVersion: v1
kind: Service
metadata:
  name: order-api
  labels:
    role: api
    {{- include "tht-devops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    role: api
    {{- include "tht-devops.selectorLabels" . | nindent 4 }}
