apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-shared-config
data:
  AWS_ACCESS_KEY_ID: {{ default "local" .Values.config.aws.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ default "local" .Values.config.aws.secretAccessKey }}
  AWS_DEFAULT_REGION: {{ default "eu-west-1" .Values.config.aws.defaultRegion }}
  DYNAMODB_ENDPOINT: {{ required "Please provide a valid dynamodb endpoint" .Values.config.dynamodb.endpoint }}
  DYNAMODB_TABLE: {{ default "orders" .Values.config.dynamodb.table }}
